# Generated by Django 5.0.3 on 2024-09-08 21:47

import localflavor.us.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(max_length=10),
        ),
    ]
